### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by rayfix** [boostcon/cppnow_website#1]
Hi!  Maybe this should just be cppnow_website (sans year).  I propose we can handle yearly updates differently going forward.

**Comment by mjcaisse** [comment]
I was just getting ready to make a new template for Jon and 2016 after talking to him on the phone. I'm all ears! What do you have in mind?

**Comment by rayfix** [comment]
What we need to preserve each year is (0) Final announcement, winners, sponsors (1) links talks / videos (2) list of participants, volunteers and what role they had.  If they really want to go back and look at what restaurant was featured on what day, etc, they can use version control feature of github.

In other words, just create a single conference website that has the most up-to-date info on the previous years.  The main reason why we were making separate websites was limitations with wordpress plugins.  It couldn't handle previous years schedules, etc.  Since that problem has gone away, I think it makes sense to build one consolidated website.

**Comment by mjcaisse** [comment]
I like the idea and I think Tyler was thinking the same. Let me see what I can throw together for a first example. Thanks!

**Comment by mjcaisse** [comment]
Basic setup to support all the years in this one spot.
